<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TorrServerManager</AssemblyName>
    <RootNamespace>TorrServerManager</RootNamespace>
    <Version>1.8.2</Version>
    <Authors>Local TorrServer Manager</Authors>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="SmartTsPlugin.js" LogicalName="TorrServerManager.SmartTsPlugin.js" />
    <EmbeddedResource Include="TorrentModPlugin.js" LogicalName="TorrServerManager.TorrentModPlugin.js" />
  </ItemGroup>
</Project>
